### ISSUE TITLE
Add documentation on traffic participants

### ISSUE THREAD

**Issue by max-rosin** [OpenSimulationInterface/osi-documentation#17]
#### Describe the feature
Traffic participants are going to be added in v3.3 of OSI. The documenation must be updated to reflect that change.

#### Describe the solution you would like
- Add the concept of traffic participants to the "vision document" (index.rst)
- Add examples for modelling traffic participants 

#### Additional context
A draft for documentation was prepared by traffic-participants workgroup.

**Comment by max-rosin** [comment]
#### To-Dos from meeting on 12th February 2021:

##### index.rst

- [ ] Redo image.
- [ ] Add separate images on traffic participant (reuse?).
- [ ] Introduce a new heading "Interfaces" above the interface descriptions.
- [ ] Add trafficUpdate interface to interface descriptions
- [ ] Add trafficCommand interface to interface descriptions.
- [ ] Consolidate "Project" section and first paragraph of "Vision" section into new "Vision" section.
- [ ] Move that consolidated "Vision" section to the top.

##### traffic-participants.rst

- [ ] Fix arrows in graphics.
- [ ] Remove HostVehiceData from graphics and text for now.
- [ ] Figure out how to integrate the document into the documentation.
